### ISSUE TITLE
Conversion for so-vits-svc 4.0 v1 not working in v 1.5.1.8 on Windows 10

### ISSUE THREAD

**Issue by 34j** [w-okada/voice-changer#141]
```shell
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-980' coro=<AsyncServer._handle_event_internal() done, defined at socketio\asyncio_server.py:522> exception=AttributeError("'SoVitsSvc40' object has no attribute 'hps'")>
Traceback (most recent call last):
  File "socketio\asyncio_server.py", line 524, in _handle_event_internal
  File "socketio\asyncio_server.py", line 569, in _trigger_event
  File "socketio\asyncio_namespace.py", line 37, in trigger_event
  File "sio\MMVC_Namespace.py", line 34, in on_request_message
  File "voice_changer\VoiceChangerManager.py", line 36, in changeVoice
  File "voice_changer\VoiceChanger.py", line 156, in on_request
  File "voice_changer\SoVitsSvc40\SoVitsSvc40.py", line 168, in get_processing_sampling_rate
AttributeError: 'SoVitsSvc40' object has no attribute 'hps'
```

**Comment by w-okada** [comment]
Maybe smae problem.

https://github.com/w-okada/voice-changer/issues/144

please refer it.
